# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rdirichletC <- function(n) {
    .Call('_SAMEclustering_rdirichletC', PACKAGE = 'SAMEclustering', n)
}

tableC <- function(x) {
    .Call('_SAMEclustering_tableC', PACKAGE = 'SAMEclustering', x)
}

EM <- function(data, M) {
    .Call('_SAMEclustering_EM', PACKAGE = 'SAMEclustering', data, M)
}

